name: Qodana

on:
  push:
    branches: [ qodana ]
    paths:
      - .github/workflows/quodana.yml
  workflow_dispatch:

jobs:
  qodana:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
