name: Qodana

on:
  push:
    branches: [ qodana ]
    paths:
      - .github/workflows/qodana.yml
  workflow_dispatch:

jobs:
  qodana:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v1.0-eap
      - run: ls -l
      - run: ls -l
        working-directory: qodana
      - run: ls -l
        working-directory: report
      - uses: actions/upload-artifact@v2
        with:
          name: qodana.json
          path: qodana/results-allProblems.json
      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: report
