name: Qodana

on:
  push:
    branches: [ qodana ]
    paths:
      - .github/workflows/qodana.yml
  workflow_dispatch:

jobs:
  qodana:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v1.0-eap

