name: Qodana

on:
  push:
    branches: [ qodana ]
    paths:
      - .github/workflows/qodana.yml

jobs:
  qodana:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v1.0-eap
        with:
          report-dir: docs
      - run: ls -l
      - run: ls -l
        working-directory: qodana
      - run: ls -l
        working-directory: docs
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/
          git commit -m "Qodana report"
          git push
      - uses: actions/upload-artifact@v2
        with:
          name: qodana jsons
          path: qodana
      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: docs
